import localFont from "next/font/local";
import NavBar from "@/components/NavBar";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="bg-gradient-to-r from-gray-900 to-gray-800">
        {/* <NavBar/> */}
        </div>

        {children}
        {/* <footer className="py-5 text-gray-400 bg-gradient-to-r from-gray-900 to-gray-800">
        <div className="container mx-auto text-center">
          <p>
            &copy; {new Date().getFullYear()} University Exam Question Paper
            Management System. All rights reserved.
          </p>
        </div>
      </footer> */}
      </body>
    </html>
  );
}
