import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "UEMS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <footer className="bg-slate-950 text-white py-2">
        <div className="container mx-auto px-1 text-center">
          <p>&copy; 2024 UEPMS. All rights reserved.</p>
        </div>
      </footer>
      <div className="fixed top-[5%] left-[5%] w-32 h-32 border border-blue-500/20 rounded-full animate-pulse" />
        <div className="fixed top-[5%] right-[5%] w-10 h-10 border border-blue-500/20 rounded-full animate-[spin_8s_linear_infinite_reverse]" />
        <div className="fixed bottom-[5%] left-[5%] w-10 h-10 border border-indigo-500/20 rounded-full animate-[spin_8s_linear_infinite_reverse]" />
        <div className="fixed bottom-[5%] right-[5%] w-32 h-32 border border-indigo-500/20 rounded-full animate-[spin_8s_linear_infinite]"/>
      </body>
    </html>
  );
}
