import { Inter } from "next/font/google";
import Head from "next/head";
import NavBar from "@/components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </Head>
      <body className={`${inter.className} body_bg`} >
        <nav className=" bg-gradient-to-r text-white px-5 py-4 shadow-lg w-full fixed top-0 left-0 nav_bg">
          <NavBar/>
        </nav>
        {children}
        <footer className="bg-gradient-to-r text-white py-3 footer_bg">
        <div className="container mx-auto text-center">
          <p className="text-sm"> 2024 &copy; University Exam Question Paper Management System.</p>
        </div>
      </footer>
      </body>
    </html>
  );
}
